%% set up
addpath(fullfile('..', 'utilities'));
addpath('animations');
if ~exist(fullfile('dynamics', 'dynamics_AUTOgenerated'), 'dir')
    run('computeEOM.m'); % compute EOM
end
addpath('dynamics');
addpath(fullfile('dynamics', 'dynamics_AUTOgenerated'));

n   = 10; % state dimension
m   = 4;  % input dimension
nXi = 4; % number of control parameters (for each input)

% passive solution at vAVG=0.05
load('contDataPassive005.mat')
idx       = numel(contData1.gamma); % select vAVG=0.05
vAVG      = contData1.vAVG(idx);
T_pas     = contData1.T(idx);
x0_pas    = contData1.x0(:,idx);
gamma_pas = contData1.gamma(idx);

gamma_end = 0;

fDstepSize = 1e-11; % finite difference step size
rootFunctionTolerance = 1e-8;
odeOpts = odeset('RelTol',1e-11,'AbsTol',1e-12); % ode solver
odeOpts.bezierVSbspline = 1; % Bezier=0, B-Spline=1
odeOpts.SolverType = @ode45;
h = 1e-2; % fixed step-size in continuation

% X = [T,x0,xi,lambda,gamma,vAVG]
% X = [z;vAVG]
X0 = [T_pas;
      x0_pas;
      zeros(nXi*m,1);
      zeros(n+2,1);
      gamma_pas;
      vAVG];

rFun = @(z) resDirect([z;vAVG],n,m,nXi,odeOpts); % fix vAVG
% z = [T,x0,xi,lambda,gamma]
z_init = X0(1:end-1);

contData = directContinuation(z_init,rFun,gamma_end,n,m,nXi,...
                              fDstepSize,rootFunctionTolerance,h);

contData.gamma = contData.sigma;
contData.vAVG  = vAVG*ones(size(contData.T));
contData = rmfield(contData, 'sigma');


%% plots
idx = [1,find(diff(contData.strictMin<0)),numel(contData.strictMin)];
figure
title(['$v_\mathrm{avg}=$',num2str(vAVG)],'Interpreter','latex')
hold on
grid on
for i=1:(numel(idx)-1)
    range = idx(i):idx(i+1);
    if contData.strictMin(idx(i)+1)>0
        plot(contData.gamma(range)*180/pi,contData.T(range),'b')
    else
        plot(contData.gamma(range)*180/pi,contData.T(range),'b--')
    end
end
xlabel('$\gamma~[^\circ]$','Interpreter','latex')
ylabel('$T$','Interpreter','latex')

figure
title(['$v_\mathrm{avg}=$',num2str(vAVG)],'Interpreter','latex')
hold on
grid on
for i=1:(numel(idx)-1)
    range = idx(i):idx(i+1);
    if contData.strictMin(idx(i)+1)>0
        plot(contData.gamma(range)*180/pi,contData.cost(range),'b')
    else
        plot(contData.gamma(range)*180/pi,contData.cost(range),'b--')
    end
end
xlabel('$\gamma~[^\circ]$','Interpreter','latex')
ylabel('cost','Interpreter','latex')

figure
title(['$v_\mathrm{avg}=$',num2str(vAVG)],'Interpreter','latex')
hold on
grid on
plot(repmat(contData.gamma*180/pi,[m*nXi,1])',contData.xi')
xlabel('$\gamma~[^\circ]$','Interpreter','latex')
ylabel('$\xi_i$','Interpreter','latex')

figure
title(['$v_\mathrm{avg}=$',num2str(vAVG)],'Interpreter','latex')
hold on
grid on
plot(repmat(contData.gamma*180/pi,[n+2,1])',contData.lambda')
xlabel('$\gamma~[^\circ]$','Interpreter','latex')
ylabel('$\lambda_i$','Interpreter','latex')

