%% set up
addpath(fullfile('..', 'utilities'));
addpath('animations');
addpath('indirect_explict_ode');
if ~exist(fullfile('dynamics', 'dynamics_AUTOgenerated'), 'dir')
    run('computeEOM.m'); % compute EOM
end
addpath('dynamics');
addpath(fullfile('dynamics', 'dynamics_AUTOgenerated'));

n   = 10; % state dimension
m   = 4;  % input dimension

% passive solution
load('contDataPassive005.mat')
idx       = numel(contData1.gamma); % select vAVG=0.05
vAVG      = contData1.vAVG(idx);
T_pas     = contData1.T(idx);
x0_pas    = contData1.x0(:,idx);
gamma_pas = contData1.gamma(idx);

gamma_end = 0;

fDstepSize = 1e-9; % finite difference step size
rootFunctionTolerance = 1e-8;
odeOpts = odeset('RelTol',1e-9,'AbsTol',1e-10); % ode solver
odeOpts.SolverType = @ode45;
h = 1e-2; % fixed step-size in continuation

% reconstruct multipliers from passive solution
%p0_pas     = zeros(10,1);
B_min = [eye(4);0 0 0 0];
M_min = M_minAUTO(x0_pas);
f_u   = [zeros(5,4);M_min\B_min];
[l,l_x,l_u,l_ux] = lFUN(x0_pas,zeros(4,1));

p0_pas     = 0*x0_pas;
q_pas      = 1/(vAVG*T_pas);
lambda_pas = zeros(2,1);

% X = [T,x0,p0,q,lambda,gamma,vAVG]
% X = [z;vAVG]
X0 = [T_pas;
      x0_pas;
      p0_pas;
      q_pas;
      lambda_pas;
      gamma_pas;
      vAVG];

rFun = @(z) resIndirect_explicit([z;vAVG],n,m,odeOpts); % fix vAVG
% z = [T,x0,p0,q,lambda,gamma]
z_init = X0(1:end-1);

contData = indirectContinuation_explicit(z_init,rFun,gamma_end,n,m,...
                                fDstepSize,rootFunctionTolerance,h);

contData.gamma = contData.sigma;
contData.vAVG  = vAVG*ones(size(contData.T));
contData = rmfield(contData, 'sigma');

%% animations
[t_,x_]=getTrajectoriesIndirect_explicit(contData.T(end),...
                                       contData.x0(:,end),...
                                       contData.p0(:,end),...
                                       contData.q(end),... 
                                       contData.gamma(end),... 
                                       vAVG,...
                                       odeOpts);
getAnimationRABBIT(interp1(t_,x_,linspace(0,t_(end),50)'),contData.gamma(end),'levelGroundIndirect005')


%% plots
figure
title(['$v_\mathrm{avg}=$',num2str(vAVG)],'Interpreter','latex')
hold on
grid on
plot(contData.gamma*180/pi,contData.T)
xlabel('$\gamma~[^\circ]$','Interpreter','latex')
ylabel('$T$','Interpreter','latex')

figure
title(['$v_\mathrm{avg}=$',num2str(vAVG)],'Interpreter','latex')
hold on
grid on
plot(contData.gamma*180/pi,contData.cost)
xlabel('$\gamma~[^\circ]$','Interpreter','latex')
ylabel('cost','Interpreter','latex')

figure
title(['$v_\mathrm{avg}=$',num2str(vAVG)],'Interpreter','latex')
hold on
grid on
plot(repmat(contData.gamma*180/pi,[n,1])',contData.p0')
xlabel('$\gamma~[^\circ]$','Interpreter','latex')
ylabel('$p_0$','Interpreter','latex')

figure
title(['$v_\mathrm{avg}=$',num2str(vAVG)],'Interpreter','latex')
hold on
grid on
plot(repmat(contData.gamma*180/pi,[n,1])',contData.q')
xlabel('$\gamma~[^\circ]$','Interpreter','latex')
ylabel('$q$','Interpreter','latex')

figure
title(['$v_\mathrm{avg}=$',num2str(vAVG)],'Interpreter','latex')
hold on
grid on
plot(repmat(contData.gamma*180/pi,[2,1])',contData.lambda')
xlabel('$\gamma~[^\circ]$','Interpreter','latex')
ylabel('$\lambda_i$','Interpreter','latex')
