%% set up
addpath(fullfile('..', 'utilities'));
addpath('animations');
if ~exist(fullfile('dynamics', 'dynamics_AUTOgenerated'), 'dir')
    run('computeEOM.m'); % compute EOM
end
addpath('dynamics');
addpath(fullfile('dynamics', 'dynamics_AUTOgenerated'));

n   = 10; % state dimension
m   = 4; % input dimension

rootFunctionTolerance = 1e-8;
odeOpts = odeset('RelTol',1e-11,'AbsTol',1e-12); % ode solver
odeOpts.SolverType = @ode45;
h = 5e-2; % fixed step-size in continuation

rFun = @(X) resPassive(X,n,m,odeOpts);


%% find branching points
% X = [T,x0,gamma]
T_span = 0.1:h:3;
x_equi = [pi;pi;zeros(8,1)];

detJac = zeros(size(T_span));
for i = 1:numel(T_span)
    T = T_span(i);
    [bifInd,Dres_min] = bifurcationIndicator(T,rFun,x_equi);
    detJac(i) = bifInd;
end

figure
grid on, hold on;
plot(T_span,detJac)

Tinits = T_span(abs(diff(sign(detJac)))>0);
disp(Tinits)

T_bifurcations = Tinits;
t_bifurcations = zeros(n+3,numel(Tinits));
X_walking      = zeros(n+3,numel(Tinits));
for i=1:numel(Tinits)
    T_bifurcations(i) = fzero(@(T) bifurcationIndicator(T,rFun,x_equi), Tinits(i) );
    [~,Dres_min] = bifurcationIndicator(T_bifurcations(i),rFun,x_equi);
    [U,S,V] = svd(Dres_min);
    t_bifurcations(:,i) = [0;V(:,end)];
    X_walking(:,i) = [T_bifurcations(i);x_equi;0;0]+h*t_bifurcations(:,i)*sign(t_bifurcations(end,i));
end


%% start continuations
vAVG_end = 0.05;
z_init = X_walking(:,1); 
contData1 = passiveContinuation(z_init,rFun,vAVG_end,n,...
                                rootFunctionTolerance,h);
idx_005 = numel(contData1.T);
vAVG_end = 0.15;
z_init = [contData1.T(idx_005);contData1.x0(:,idx_005);contData1.gamma(idx_005);contData1.vAVG(idx_005)]; 
contData2 = passiveContinuation(z_init,rFun,vAVG_end,n,...
                                rootFunctionTolerance,h);


%% animations
idx = idx_005;
[t_,x_]=getTrajectoriesPassive(contData1.T(idx),...
                               contData1.x0(:,idx),...
                               contData1.gamma(idx),... 
                               m,odeOpts);
getAnimationRABBIT(interp1(t_,x_,linspace(0,t_(end),30)'),contData1.gamma(idx),'passive005')

%% plots
figure
hold on
grid on
plot(contData1.gamma*180/pi,contData1.T)
plot(contData2.gamma*180/pi,contData2.T)
xlabel('$\gamma~[^\circ]$','Interpreter','latex')
ylabel('$T$','Interpreter','latex')

figure
hold on
grid on
xlabel('$\gamma~[^\circ]$','Interpreter','latex')
ylabel('$v_\mathrm{avg}$','Interpreter','latex')
plot(contData1.gamma*180/pi,contData1.vAVG);
plot(contData2.gamma*180/pi,contData2.vAVG);



